mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_1.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_2.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_3.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_4.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_5.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_6.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_7.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_8.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_9.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_10.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_11.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_12.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_13.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_14.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_15.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_16.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_17.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_18.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_19.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_20.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_21.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_22.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_23.txt
mail -s "Aviso documento legal" GERARDO.PALMA.ASTE@GMAIL.COM < /home/cpalma/git/bt5/BT5/00300_erp_bt5/01700_crontabs/mandar_aviso_por_dole/arch_24.txt
