--set client_min_messages to warning;

insert into monedas values (1  , 'PESO CHILENO'             , 'CLP');
insert into monedas values (2  , 'PESO ARGENTINO'           , 'ARS');
insert into monedas values (3  , 'NUEVO SOL'                , 'PEN');
insert into monedas values (4  , 'BOLIVIANO'                , 'BOB');
insert into monedas values (5  , 'GUARANÍ'                  , 'PYG');
insert into monedas values (6  , 'PESO URUGUAYO'            , 'UYU');
insert into monedas values (7  , 'REAL'                     , 'BRL');
insert into monedas values (8  , 'SUCRE'                    , 'ECS');
insert into monedas values (9  , 'BOLIVAR'                  , 'VEB');
insert into monedas values (10 , 'PESO COLOMBIANO'          , 'COP');
insert into monedas values (11 , 'DÓLAR'                    , 'USD');
insert into monedas values (501, 'UNIDAD DE FOMENTO'        , 'UF' );
insert into monedas values (502, 'UNIDAD TRIBUTARIA MENSUAL', 'UTM' );

insert into paises values (1 , 'CHILE'    , 1 , 'CHILENA'    );
insert into paises values (2 , 'ARGENTINA', 2 , 'ARGENTINA'  );
insert into paises values (3 , 'PERU'     , 3 , 'PERUANA'    );
insert into paises values (4 , 'BOLIVIA'  , 4 , 'BOLIVIANA'  );
insert into paises values (5 , 'PARAGUAY' , 5 , 'PARAGUAYA'  );
insert into paises values (6 , 'URUGUAY'  , 6 , 'URUGUAYA'   );
insert into paises values (7 , 'BRASIL'   , 7 , 'BRASILENA'  );
insert into paises values (8 , 'ECUADOR'  , 8 , 'ECUATORIANA');
insert into paises values (9 , 'VENEZUELA', 9 , 'VENEZOLANA' );
insert into paises values (10, 'COLOMBIA' , 10, 'COLOMBIANA' );

/* Deshabilito algunas constraints para poder insertar datos iniciales */
alter table usuarios                   disable trigger all;
alter table personas                   disable trigger all;
alter table grupos_empresariales       drop constraint grem_fk1_usua;
alter table parametros                 drop constraint para_fk1_usua;
alter table planes_cuentas             drop constraint plcu_fk1_usua;
alter table tipos_documentos_legales   drop constraint tidl_fk1_usua;
alter table estados_documentos_legales drop constraint esdl_fk1_usua;

insert into estados_registros values (1, 'ACTIVO'  );
insert into estados_registros values (2, 'INACTIVO');

insert into estados_grem values (1, 'ACTIVO'    );
insert into estados_grem values (2, 'INACTIVO'  );
insert into estados_grem values (3, 'SUSPENDIDO');

insert into estados_civiles values (1, 'S', 'SOLTERO' );
insert into estados_civiles values (2, 'C', 'CASADO'  );
insert into estados_civiles values (3, 'V', 'VIUDO'   );
insert into estados_civiles values (4, 'E', 'SEPARADO');

insert into sexos values (1, 'M', 'MASCULINO');
insert into sexos values (2, 'F', 'FEMENINO' );

insert into tipos_doctos_ventas values (1, 1, 'NO DEFINIDO'                 , 'NODE',  0);
insert into tipos_doctos_ventas values (2, 1, 'FACTURA ELECTRÓNICA'         , 'FAEA', 33);
insert into tipos_doctos_ventas values (3, 1, 'NOTA DE CRÉDITO ELECTRÓNICA' , 'NCEL', 61);
insert into tipos_doctos_ventas values (4, 1, 'GUÍA DE DESPACHO ELECTRÓNICA', 'GDEL', 52);

insert into grupos_empresariales values (1, 'BUSINESS & TECHNOLOGY 5 CONSULTING', 'BT5', 'bt5.jpg', 1, 1, 1, current_timestamp, null, null, null, null);

insert into personas values (1, 1, 1, '9', 'ADMINISTRADOR', null, 'SISTEMA', 'AS', null, null, null, null, null, 1, current_timestamp, null, null, null, null);

insert into usuarios values (1, 'ADMIN', '12345', 1, 1, 1, current_timestamp, null, null, null, null);

alter table usuarios add constraint usua_fk_pers foreign key (idpers) references personas (id);

/* Rehabilito constraints deshabilitadas */
alter table usuarios                   enable trigger all;
alter table personas                   enable trigger all;
alter table grupos_empresariales       add constraint grem_fk1_usua foreign key (idusuacrearegistro) references usuarios(id);
alter table parametros                 add constraint para_fk1_usua foreign key (idusuacrearegistro) references usuarios(id);
alter table planes_cuentas             add constraint plcu_fk1_usua foreign key (idusuacrearegistro) references usuarios(id);
alter table tipos_documentos_legales   add constraint tidl_fk1_usua foreign key (idusuacrearegistro) references usuarios(id);
alter table estados_documentos_legales add constraint esdl_fk1_usua foreign key (idusuacrearegistro) references usuarios(id);

insert into personas values (2 , 1, 2       , '7', 'ROLANDO'    , null      , 'SILVA'    , '-'        ,  ''                            , null        , 2   , 1, 1, 1, current_timestamp, null, null, null, null);
insert into personas values (3 , 1, 3       , '5', 'SERGIO'     , null      , 'AGUIRRE'  , '-'        ,  'sergio.aguirre@bt5.cl'       , null        , 1   , 1, 1, 1, current_timestamp, null, null, null, null);
insert into personas values (4 , 1, 4       , '3', 'JUAN'       , 'JOSE'    , 'MONSALVE' , '-'        ,  'juan.jose.monsalve@bt5.cl'   , null        , null, 1, 1, 1, current_timestamp, null, null, null, null);
insert into personas values (5 , 1, 5       , '1', 'JUAN'       , 'ANDRES'  , 'BORZONE'  , '-'        ,  ''                            , null        , null, 1, 1, 1, current_timestamp, null, null, null, null);
insert into personas values (6 , 1, 6       , 'K', 'RODRIGO'    , null      , 'CIFUENTES', '-'        ,  'rodrigo.cifuentes@bt5.cl'    , null        , 1   , 1, 1, 1, current_timestamp, null, null, null, null);
insert into personas values (7 , 1, 7695503 , '4', 'ROBERTO'    , 'DANIEL'  , 'QUEZADA'  , 'ASTE'     ,  'roberto.quezada@bt5.cl'      , null        , 2   , 1, 1, 1, current_timestamp, null, null, null, null);
insert into personas values (8 , 1, 8965445 , '9', 'OSCIEL'     , 'SEGUNDO' , 'SOLAR'    , 'MALDONADO',  'solar2design@gmail.com'      , null        , 2   , 1, 1, 1, current_timestamp, null, null, null, null);
insert into personas values (9 , 1, 13254825, '0', 'NILTON'     , 'PATRICIO', 'SALAZAR'  , 'GONZALEZ' ,  'nilton.salazar@gmail.com'    , null        , 1   , 1, 1, 1, current_timestamp, null, null, null, null);
insert into personas values (10, 1, 10917721, '0', 'G. CRISTIAN', null      , 'PALMA'    , 'ASTE'     ,  'gerardo.palma.aste@gmail.com', '12-11-1968', 1   , 1, 1, 1, current_timestamp, null, null, null, null);

insert into usuarios values (2 , 'ROSILVA'    , '12345', 2 , 1, 1, current_timestamp, null, null, null, null);
insert into usuarios values (3 , 'SEAGUIRRE'  , '12345', 3 , 1, 1, current_timestamp, null, null, null, null);
insert into usuarios values (4 , 'JJMONSALVE' , '12345', 4 , 1, 1, current_timestamp, null, null, null, null);
insert into usuarios values (5 , 'JABORZONE'  , '12345', 5 , 1, 1, current_timestamp, null, null, null, null);
insert into usuarios values (6 , 'ROCIFUENTES', '12345', 6 , 1, 1, current_timestamp, null, null, null, null);
insert into usuarios values (7 , 'RQUEZADAA'  , '12345', 7 , 2, 1, current_timestamp, null, null, null, null);
insert into usuarios values (8 , 'OSOLARM'    , '12345', 8 , 1, 1, current_timestamp, null, null, null, null);
insert into usuarios values (9 , 'NSALAZARG'  , '12345', 9 , 1, 1, current_timestamp, null, null, null, null);
insert into usuarios values (10, 'CPALMAA'    , '12345', 10, 1, 1, current_timestamp, null, null, null, null);

insert into empresas values (1 , 1, 1, 1, 1, '1', '9', 'BUSINESS & TECHNOLOGY 5 CONSULTING', 'BT5', 'bt5.jpg', 1, current_timestamp, null, null, null, null, null);

insert into valores_paises values (nextval('vapa_seq'), 1 , 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'RUT'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 1 , 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 1 , 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUT'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 1 , 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 1 , 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 1 , 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 1 , 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 1 , 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 1 , 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);
--
insert into valores_paises values (nextval('vapa_seq'), 2 , 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'DNI'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 2 , 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 2 , 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUT'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 2 , 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 2 , 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 2 , 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 2 , 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 2 , 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 2 , 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);
--
insert into valores_paises values (nextval('vapa_seq'), 3 , 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 3 , 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 3 , 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 3 , 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 3 , 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 3 , 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 3 , 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 3 , 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 3 , 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);
--
insert into valores_paises values (nextval('vapa_seq'), 4 , 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 4 , 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 4 , 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 4 , 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 4 , 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 4 , 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 4 , 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 4 , 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 4 , 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);
--
insert into valores_paises values (nextval('vapa_seq'), 5 , 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 5 , 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 5 , 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 5 , 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 5 , 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 5 , 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 5 , 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 5 , 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 5 , 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);
--
insert into valores_paises values (nextval('vapa_seq'), 6 , 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 6 , 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 6 , 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 6 , 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 6 , 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 6 , 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 6 , 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 6 , 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 6 , 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);
--
insert into valores_paises values (nextval('vapa_seq'), 7 , 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 7 , 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 7 , 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 7 , 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 7 , 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 7 , 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 7 , 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 7 , 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 7 , 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);
--
insert into valores_paises values (nextval('vapa_seq'), 8 , 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 8 , 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 8 , 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 8 , 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 8 , 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 8 , 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 8 , 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 8 , 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 8 , 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);
--
insert into valores_paises values (nextval('vapa_seq'), 9 , 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 9 , 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 9 , 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 9 , 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 9 , 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 9 , 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 9 , 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 9 , 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 9 , 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);
--
insert into valores_paises values (nextval('vapa_seq'), 10, 'IDENTP1', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 1 TABLA PERSONAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 10, 'IDENTP2', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS', 'ETIQUETA IDENTIFICADOR 2 TABLA PERSONAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 10, 'IDENTE1', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 1 TABLA EMPRESAS'                , 'RUC'       ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 10, 'IDENTE2', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS', 'ETIQUETA IDENTIFICADOR 2 TABLA EMPRESAS'                , 'DV'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 10, 'RETHON' , 'RETENCIÓN HONORARIOS'                   , '% RETENCIÓN DE HONORARIOS EN ESTE PAIS'                 , '10'        ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 10, 'NUMUNIT', 'NRO. UNIDADES TERRITORIALES'            , 'NRO. DE UNIDADES TERRITORIALES EN QUE SE DIVIDE EL PAIS', '3'         ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 10, 'UNITER1', 'UNIDAD TERRITORIAL ORDEN 1'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 1'                   , 'REGIÓN'    ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 10, 'UNITER2', 'UNIDAD TERRITORIAL ORDEN 2'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 2'                   , 'PROVINCIA' ,  1, current_timestamp, null, null, null, null);
insert into valores_paises values (nextval('vapa_seq'), 10, 'UNITER3', 'UNIDAD TERRITORIAL ORDEN 3'             , 'NOMBRE UNIDAD TERRITORIAL DE ORDEN 3'                   , 'COMUNA'    ,  1, current_timestamp, null, null, null, null);

insert into estados_solics_servs_hono values (1, 'CREADA'                           );
insert into estados_solics_servs_hono values (2, 'TRANSFERIDA A JEFE DE COMPRAS'    );
insert into estados_solics_servs_hono values (3, 'EN PROCESO'                       );
insert into estados_solics_servs_hono values (4, 'ACEPTADA UNA COTIZACIÓN'          );
insert into estados_solics_servs_hono values (5, 'RECHAZADAS TODAS LAS COTIZACIONES');

insert into estados_cotizacs_servs_hono values (1, 'RECIBIDA' );
insert into estados_cotizacs_servs_hono values (2, 'ACEPTADA' );
insert into estados_cotizacs_servs_hono values (3, 'RECHAZADA');

insert into estados_ordenes_servs_hono values (1, 'CREADA'                                          );
insert into estados_ordenes_servs_hono values (2, 'ASIGNADA A PROFESIONAL'                          );
insert into estados_ordenes_servs_hono values (3, 'TERMINADA EXITOSAMENTE (APROBADO EL TRABAJO)'    );
insert into estados_ordenes_servs_hono values (4, 'TERMINADA NO EXITOSAMENTE (RECHAZADO EL TRABAJO)');

insert into estados_pagos_ords_servs_hono values (1, 'CREADO');
insert into estados_pagos_ords_servs_hono values (2, 'PAGADO');

insert into unidades_territoriales_1 (id, idpais, nombre) values (1 , 1, 'REGIÓN DE TARAPACÁ'                                 );
insert into unidades_territoriales_1 (id, idpais, nombre) values (2 , 1, 'REGIÓN DE ANTOFAGASTA'                              );
insert into unidades_territoriales_1 (id, idpais, nombre) values (3 , 1, 'REGIÓN DE ATACAMA'                                  );
insert into unidades_territoriales_1 (id, idpais, nombre) values (4 , 1, 'REGIÓN DE COQUIMBO'                                 );
insert into unidades_territoriales_1 (id, idpais, nombre) values (5 , 1, 'REGIÓN DE VALPARAÍSO'                               );
insert into unidades_territoriales_1 (id, idpais, nombre) values (6 , 1, 'REGIÓN DEL LIBERTADOR GENERAL BERNARDO O''HIGGINS'  );
insert into unidades_territoriales_1 (id, idpais, nombre) values (7 , 1, 'REGIÓN DEL MAULE'                                   );
insert into unidades_territoriales_1 (id, idpais, nombre) values (8 , 1, 'REGIÓN DEL BIOBÍO'                                  );
insert into unidades_territoriales_1 (id, idpais, nombre) values (9 , 1, 'REGIÓN DE LA ARAUCANÍA'                             );
insert into unidades_territoriales_1 (id, idpais, nombre) values (10, 1, 'REGIÓN DE LOS LAGOS'                                );
insert into unidades_territoriales_1 (id, idpais, nombre) values (11, 1, 'REGIÓN DE AISÉN DEL GENERAL CARLOS IBAÑEZ DEL CAMPO');
insert into unidades_territoriales_1 (id, idpais, nombre) values (12, 1, 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA'     );
insert into unidades_territoriales_1 (id, idpais, nombre) values (13, 1, 'REGIÓN METROPOLITANA DE SANTIAGO'                   );
insert into unidades_territoriales_1 (id, idpais, nombre) values (14, 1, 'REGIÓN DE LOS RÍOS'                                 );
insert into unidades_territoriales_1 (id, idpais, nombre) values (15, 1, 'REGIÓN DE ARICA Y PARINACOTA'                       );
insert into unidades_territoriales_1 (id, idpais, nombre) values (16, 1, 'REGIÓN DEL ÑUBLE'                                   );

insert into unidades_territoriales_2 (id, idunt1, nombre) values (1 , 1 , 'IQUIQUE'                );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (2 , 1 , 'TAMARUGAL'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (3 , 2 , 'TOCOPILLA'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (4 , 2 , 'EL LOA'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (5 , 2 , 'ANTOFAGASTA'            );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (6 , 3 , 'CHAÑARAL'               );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (7 , 3 , 'COPIAPÓ'                );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (8 , 3 , 'HUASCO'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (9 , 4 , 'ELQUI'                  );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (10, 4 , 'LIMARI'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (11, 4 , 'CHOAPA'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (12, 5 , 'PETORCA'                );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (13, 5 , 'SAN FELIPE DE ACONCAGUA');
insert into unidades_territoriales_2 (id, idunt1, nombre) values (14, 5 , 'QUILLOTA'               );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (15, 5 , 'LOS ANDES'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (16, 5 , 'VALPARAISO'             );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (17, 5 , 'SAN ANTONIO'            );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (18, 5 , 'ISLA DE PASCUA'         );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (19, 6 , 'CACHAPOAL'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (20, 6 , 'CARDENAL CARO'          );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (21, 6 , 'COLCHAGUA'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (22, 7 , 'CURICÓ'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (23, 7 , 'TALCA'                  );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (24, 7 , 'CAUQUENES'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (25, 7 , 'LINARES'                );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (26, 8 , 'ÑUBLE'                  );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (27, 8 , 'CONCEPCIÓN'             );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (28, 8 , 'BIOBÍO'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (29, 8 , 'ARAUCO'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (30, 9 , 'MALLECO'                );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (31, 9 , 'CAUTIN'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (32, 10, 'OSORNO'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (33, 10, 'LLANQUIHUE'             );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (34, 10, 'CHILOE'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (35, 10, 'PALENA'                 );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (36, 11, 'AISÉN'                  );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (37, 11, 'COYHAIQUE'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (38, 11, 'GENERAL CARRERA'        );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (39, 11, 'CAPITAN PRAT'           );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (40, 12, 'ULTIMA ESPERANZA'       );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (41, 12, 'MAGALLANES'             );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (42, 12, 'TIERRA DEL FUEGO'       );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (43, 12, 'ANTARTICA CHILENA'      );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (44, 13, 'SANTIAGO'               );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (45, 13, 'CHACABUCO'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (46, 13, 'MELIPILLA'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (47, 13, 'TALAGANTE'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (48, 13, 'MAIPO'                  );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (49, 13, 'CORDILLERA'             );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (50, 14, 'VALDIVIA'               );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (51, 14, 'RANCO'                  );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (52, 15, 'PARINACOTA'             );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (53, 15, 'ARICA'                  );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (54, 16, 'ITATA'                  );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (55, 16, 'DIGUILLIN'              );
insert into unidades_territoriales_2 (id, idunt1, nombre) values (56, 16, 'PUNILLA'                );

insert into unidades_territoriales_3 (id, idunt2, nombre) values (1  , 1 , 'IQUIQUE'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (2  , 1 , 'ALTO HOSPICIO'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (3  , 2 , 'HUARA'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (4  , 2 , 'CAMIÑA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (5  , 2 , 'COLCHANE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (6  , 2 , 'POZO ALMONTE'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (7  , 2 , 'PICA'                );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (8  , 3 , 'TOCOPILLA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (9  , 3 , 'MARIA ELENA'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (10 , 4 , 'CALAMA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (11 , 4 , 'OLLAGÜE'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (12 , 4 , 'SAN PEDRO DE ATACAMA');
insert into unidades_territoriales_3 (id, idunt2, nombre) values (13 , 5 , 'MEJILLONES'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (14 , 5 , 'SIERRA GORDA'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (15 , 5 , 'ANTOFAGASTA'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (16 , 5 , 'TALTAL'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (17 , 6 , 'CHAÑARAL'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (18 , 6 , 'DIEGO DE ALMAGRO'    );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (19 , 7 , 'CALDERA'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (20 , 7 , 'COPIAPÓ'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (21 , 7 , 'TIERRA AMARILLA'     );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (22 , 8 , 'HUASCO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (23 , 8 , 'VALLENAR'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (24 , 8 , 'FREIRINA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (25 , 8 , 'ALTO DEL CARMEN'     );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (26 , 9 , 'LA HIGUERA'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (27 , 9 , 'VICUÑA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (28 , 9 , 'LA SERENA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (29 , 9 , 'COQUIMBO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (30 , 9 , 'ANDACOLLO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (31 , 9 , 'PAIHUANO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (32 , 10, 'OVALLE'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (33 , 10, 'RIO HURTADO'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (34 , 10, 'PUNITAQUI'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (35 , 10, 'MONTE PATRIA'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (36 , 10, 'COMBARBALÁ'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (37 , 11, 'CANELA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (38 , 11, 'ILLAPEL'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (39 , 11, 'LOS VILOS'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (40 , 11, 'SALAMANCA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (41 , 12, 'PETORCA'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (42 , 12, 'LA LIGUA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (43 , 12, 'CABILDO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (44 , 12, 'PAPUDO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (45 , 12, 'ZAPALLAR'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (46 , 13, 'PUTAENDO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (47 , 13, 'CATEMU'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (48 , 13, 'SAN FELIPE'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (49 , 13, 'SANTA MARIA'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (50 , 13, 'PANQUEHUE'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (51 , 13, 'LLAILLAY'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (52 , 14, 'NOGALES'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (53 , 14, 'LA CALERA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (54 , 14, 'LA CRUZ'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (55 , 14, 'QUILLOTA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (56 , 14, 'HIJUELAS'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (57 , 14, 'LIMACHE'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (58 , 14, 'OLMUE'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (59 , 15, 'SAN ESTEBAN'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (60 , 15, 'RINCONADA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (61 , 15, 'CALLE LARGA'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (62 , 15, 'LOS ANDES'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (63 , 16, 'PUCHUNCAVI'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (64 , 16, 'JUAN FERNANDEZ'      );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (65 , 16, 'QUINTERO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (66 , 16, 'VINA DEL MAR'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (67 , 16, 'VILLA ALEMANA'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (68 , 16, 'VALPARAISO'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (69 , 16, 'QUILPUE'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (70 , 16, 'CASABLANCA'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (71 , 16, 'CONCÓN'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (72 , 17, 'ALGARROBO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (73 , 17, 'EL QUISCO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (74 , 17, 'EL TABO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (75 , 17, 'CARTAGENA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (76 , 17, 'SAN ANTONIO'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (77 , 17, 'SANTO DOMINGO'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (78 , 18, 'ISLA DE PASCUA'      );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (79 , 19, 'MOSTAZAL'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (80 , 19, 'GRANEROS'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (81 , 19, 'CODEGUA'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (82 , 19, 'RANCAGUA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (83 , 19, 'MACHALI'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (84 , 19, 'LAS CABRAS'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (85 , 19, 'COLTAUCO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (86 , 19, 'DONIHUE'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (87 , 19, 'OLIVAR'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (88 , 19, 'COINCO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (89 , 19, 'REQUINOA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (90 , 19, 'PEUMO'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (91 , 19, 'QUINTA DE TILCOCO'   );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (92 , 19, 'PICHIDEGUA'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (93 , 19, 'SAN VICENTE'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (94 , 19, 'MALLOA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (95 , 19, 'RENGO'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (96 , 20, 'NAVIDAD'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (97 , 20, 'LITUECHE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (98 , 20, 'LA ESTRELLA'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (99 , 20, 'PICHILEMU'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (100, 20, 'MARCHIHUE'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (101, 20, 'PAREDONES'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (102, 21, 'PERALILLO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (103, 21, 'PALMILLA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (104, 21, 'SAN FERNANDO'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (105, 21, 'PUMANQUE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (106, 21, 'SANTA CRUZ'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (107, 21, 'NANCAGUA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (108, 21, 'PLACILLA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (109, 21, 'LOLOL'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (110, 21, 'CHEPICA'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (111, 21, 'CHIMBARONGO'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (112, 22, 'TENO'                );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (113, 22, 'VICHUQUÉN'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (114, 22, 'HUALAÑE'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (115, 22, 'RAUCO'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (116, 22, 'CURICÓ'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (117, 22, 'ROMERAL'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (118, 22, 'LICANTÉN'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (119, 22, 'SAGRADA FAMILIA'     );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (120, 22, 'MOLINA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (121, 23, 'CUREPTO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (122, 23, 'RIO CLARO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (123, 23, 'CONSTITUCIÓN'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (124, 23, 'PENCAHUE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (125, 23, 'TALCA'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (126, 23, 'PELARCO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (127, 23, 'SAN CLEMENTE'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (128, 23, 'MAULE'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (129, 23, 'EMPEDRADO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (130, 23, 'SAN RAFAEL'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (131, 24, 'CHANCO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (132, 24, 'CAUQUENES'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (133, 24, 'PELLUHUE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (134, 25, 'SAN JAVIER'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (135, 25, 'VILLA ALEGRE'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (136, 25, 'YERBAS BUENAS'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (137, 25, 'COLBUN'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (138, 25, 'LINARES'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (139, 25, 'RETIRO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (140, 25, 'LONGAVI'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (141, 25, 'PARRAL'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (163, 27, 'TOME'                );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (164, 27, 'FLORIDA'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (165, 27, 'TALCAHUANO'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (166, 27, 'HUALPÉN'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (167, 27, 'PENCO'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (168, 27, 'CONCEPCIÓN'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (169, 27, 'SAN PEDRO DE LA PAZ' );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (170, 27, 'CHIGUAYANTE'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (171, 27, 'HUALQUI'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (172, 27, 'CORONEL'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (173, 27, 'LOTA'                );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (174, 27, 'SANTA JUANA'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (175, 27, 'YUMBEL'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (176, 28, 'CABRERO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (177, 28, 'TUCAPEL'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (178, 28, 'ANTUCO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (179, 28, 'SAN ROSENDO'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (180, 28, 'LAJA'                );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (181, 28, 'LOS ANGELES'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (182, 28, 'QUILLECO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (183, 28, 'SANTA BÁRBARA'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (184, 28, 'ALTO BIOBÍO'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (185, 28, 'NACIMIENTO'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (186, 28, 'NEGRETE'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (187, 28, 'QUILACO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (188, 28, 'MULCHÉN'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (189, 29, 'ARAUCO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (190, 29, 'CURANILAHUE'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (191, 29, 'LEBU'                );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (192, 29, 'LOS ALAMOS'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (193, 29, 'CAÑETE'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (194, 29, 'CONTULMO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (195, 29, 'TIRUA'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (196, 30, 'ANGOL'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (197, 30, 'RENAICO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (198, 30, 'COLLIPULLI'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (199, 30, 'PURÉN'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (200, 30, 'LOS SAUCES'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (201, 30, 'ERCILLA'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (202, 30, 'LONQUIMAY'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (203, 30, 'LUMACO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (204, 30, 'TRAIGUÉN'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (205, 30, 'VICTORIA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (206, 30, 'CURACAUTIN'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (207, 31, 'GALVARINO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (208, 31, 'PERQUENCO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (209, 31, 'CARAHUE'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (210, 31, 'NUEVA IMPERIAL'      );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (211, 31, 'CHOLCHOL'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (212, 31, 'TEMUCO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (213, 31, 'PADRE LAS CASAS'     );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (214, 31, 'LAUTARO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (215, 31, 'VILCUN'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (216, 31, 'MELIPEUCO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (217, 31, 'SAAVEDRA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (218, 31, 'TEODORO SCHMIDT'     );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (219, 31, 'FREIRE'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (220, 31, 'CUNCO'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (221, 31, 'TOLTÉN'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (222, 31, 'PITRUFQUÉN'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (223, 31, 'GORBEA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (224, 31, 'LONCOCHE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (225, 31, 'VILLARRICA'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (226, 31, 'PUCÓN'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (227, 31, 'CURARREHUE'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (228, 32, 'SAN JUAN DE LA COSTA');
insert into unidades_territoriales_3 (id, idunt2, nombre) values (229, 32, 'SAN PABLO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (230, 32, 'OSORNO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (231, 32, 'PUYEHUE'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (232, 32, 'RIO NEGRO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (233, 32, 'PUERTO OCTAY'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (234, 32, 'PURRANQUE'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (235, 33, 'FRESIA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (236, 33, 'FRUTILLAR'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (237, 33, 'PUERTO VARAS'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (238, 33, 'LLANQUIHUE'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (239, 33, 'LOS MUERMOS'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (240, 33, 'PUERTO MONTT'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (241, 33, 'COCHAMO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (242, 33, 'MAULLIN'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (243, 33, 'CALBUCO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (244, 34, 'ANCUD'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (245, 34, 'QUEMCHI'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (246, 34, 'DALCAHUE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (247, 34, 'CASTRO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (248, 34, 'CURACO DE VELEZ'     );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (249, 34, 'QUINCHAO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (250, 34, 'CHONCHI'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (251, 34, 'PUQUELDÓN'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (252, 34, 'QUEILÉN'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (253, 34, 'QUELLÓN'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (254, 35, 'HUALAIHUE'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (255, 35, 'CHAITÉN'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (256, 35, 'FUTALEUFU'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (257, 35, 'PALENA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (258, 36, 'GUAITECAS'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (259, 36, 'CISNES'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (260, 36, 'AISÉN'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (261, 37, 'LAGO VERDE'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (262, 37, 'COYHAIQUE'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (263, 38, 'RIO IBANEZ'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (264, 38, 'CHILE CHICO'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (265, 39, 'COCHRANE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (266, 39, 'TORTEL'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (267, 39, 'O''HIGGINS'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (268, 40, 'NATALES'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (269, 40, 'TORRES DEL PAINE'    );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (270, 41, 'LAGUNA BLANCA'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (271, 41, 'SAN GREGORIO'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (272, 41, 'RIO VERDE'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (273, 41, 'PUNTA ARENAS'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (274, 42, 'PRIMAVERA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (275, 42, 'PORVENIR'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (276, 42, 'TIMAUKEL'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (277, 43, 'CABO DE HORNOS'      );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (278, 43, 'ANTARTICA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (279, 44, 'SANTIAGO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (280, 44, 'CERRILLOS'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (281, 44, 'CERRO NAVIA'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (282, 44, 'CONCHALI'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (283, 44, 'EL BOSQUE'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (284, 44, 'ESTACION CENTRAL'    );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (285, 44, 'HUECHURABA'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (286, 44, 'INDEPENDENCIA'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (287, 44, 'LA CISTERNA'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (288, 44, 'LA FLORIDA'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (289, 44, 'LA GRANJA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (290, 44, 'LA PINTANA'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (291, 44, 'LA REINA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (292, 44, 'LAS CONDES'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (293, 44, 'LO BARNECHEA'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (294, 44, 'LO ESPEJO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (295, 44, 'LO PRADO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (296, 44, 'MACUL'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (297, 44, 'MAIPU'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (298, 44, 'ÑUÑOA'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (299, 44, 'PEDRO AGUIRRE CERDA' );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (300, 44, 'PEÑALOLÉN'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (301, 44, 'PROVIDENCIA'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (302, 44, 'PUDAHUEL'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (303, 44, 'QUILICURA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (304, 44, 'QUINTA NORMAL'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (305, 44, 'RECOLETA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (306, 44, 'RENCA'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (307, 44, 'SAN JOAQUIN'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (308, 44, 'SAN MIGUEL'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (309, 44, 'SAN RAMÓN'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (310, 44, 'VITACURA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (311, 45, 'TILTIL'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (312, 45, 'COLINA'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (313, 45, 'LAMPA'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (314, 46, 'CURACAVI'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (315, 46, 'MARIA PINTO'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (316, 46, 'MELIPILLA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (317, 46, 'SAN PEDRO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (318, 46, 'ALHUE'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (319, 47, 'PEÑAFLOR'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (320, 47, 'EL MONTE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (321, 47, 'TALAGANTE'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (322, 47, 'ISLA DE MAIPO'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (323, 47, 'PADRE HURTADO'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (324, 48, 'CALERA DE TANGO'     );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (325, 48, 'SAN BERNARDO'        );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (326, 48, 'BUIN'                );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (327, 48, 'PAINE'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (328, 49, 'PUENTE ALTO'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (329, 49, 'PIRQUE'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (330, 49, 'SAN JOSE DE MAIPO'   );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (331, 50, 'MARIQUINA'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (332, 50, 'LANCO'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (333, 50, 'PANGUIPULLI'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (334, 50, 'MAFIL'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (335, 50, 'VALDIVIA'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (336, 50, 'LOS LAGOS'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (337, 50, 'CORRAL'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (338, 50, 'PAILLACO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (339, 51, 'FUTRONO'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (340, 51, 'LA UNIÓN'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (341, 51, 'LAGO RANCO'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (342, 51, 'RIO BUENO'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (343, 52, 'GENERAL LAGOS'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (344, 52, 'PUTRE'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (345, 53, 'ARICA'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (346, 53, 'CAMARONES'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (347, 54, 'COBQUECURA'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (348, 54, 'COELEMU'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (349, 54, 'NINHUE'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (350, 54, 'PORTEZUELO'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (351, 54, 'QUIRIHUE'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (352, 54, 'RANQUIL'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (353, 54, 'TREGUACO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (354, 55, 'BULNES'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (355, 55, 'CHILLAN VIEJO'       );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (356, 55, 'CHILLAN'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (357, 55, 'EL CARMEN'           );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (358, 55, 'PEMUCO'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (359, 55, 'PINTO'               );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (360, 55, 'QUILLÓN'             );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (361, 55, 'SAN IGNACIO'         );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (362, 55, 'YUNGAY'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (363, 56, 'COIHUECO'            );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (364, 56, 'ÑIQUÉN'              );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (365, 56, 'SAN CARLOS'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (366, 56, 'SAN FABIAN'          );
insert into unidades_territoriales_3 (id, idunt2, nombre) values (367, 56, 'SAN NICOLAS'         );

insert into tipos_clientes values (1, 'PERSONA NATURAL');
insert into tipos_clientes values (2, 'EMPRESA'        );

insert into tipos_cotizaciones_vtas values (1, 'PRESUPUESTO');
insert into tipos_cotizaciones_vtas values (2, 'PROSPECTO'  );

insert into tipos_movimientos_bodegas values (1, 'SALIDA POR VENTA'                  , -1);
insert into tipos_movimientos_bodegas values (2, 'ENTRADA POR ADQUISICIÓN'           ,  1);
insert into tipos_movimientos_bodegas values (3, 'SALIDA POR TRASPASO ENTRE BODEGAS' , -1);
insert into tipos_movimientos_bodegas values (4, 'ENTRADA POR TRASPASO ENTRE BODEGAS',  1);
insert into tipos_movimientos_bodegas values (5, 'ENTRADA POR DEVOLUCIÓN'            ,  1);

insert into estados_cotizaciones_vtas values (1, 'CREADA'  );
insert into estados_cotizaciones_vtas values (2, 'CERRADA' );
insert into estados_cotizaciones_vtas values (3, 'ACEPTADA');
insert into estados_cotizaciones_vtas values (4, 'CADUCADA');

insert into estados_notas_vtas values (1, 'CREADA'  );
insert into estados_notas_vtas values (2, 'CERRADA' );
insert into estados_notas_vtas values (3, 'EMITIDA' );
insert into estados_notas_vtas values (4, 'CADUCADA');

insert into estados_ventas values (1, 'CREADA' );
insert into estados_ventas values (2, 'CERRADA');
insert into estados_ventas values (3, 'ANULADA');

insert into origenes_productos values (1, 'NACIONAL' , 'NAC');
insert into origenes_productos values (2, 'IMPORTADO', 'IMP');

insert into unidades_medidas_productos values (1, 'MILÍGRAMOS' , 'MG');
insert into unidades_medidas_productos values (2, 'GRAMOS'     , 'GR');
insert into unidades_medidas_productos values (3, 'KILÓGRAMOS' , 'KG');
insert into unidades_medidas_productos values (4, 'MILÍMETROS' , 'MM');
insert into unidades_medidas_productos values (5, 'CENTÍMETROS', 'CM');
insert into unidades_medidas_productos values (6, 'METROS'     , 'MT');
insert into unidades_medidas_productos values (7, 'MILÍLITROS' , 'ML');
insert into unidades_medidas_productos values (8, 'LITROS'     , 'LT');
insert into unidades_medidas_productos values (9, 'UNIDADES'   , 'UN');

insert into unidades_medidas_servicios values (1, 'HORAS HOMBRE', 'HH');

insert into tipos_productos values (1 , 'ARTICULOS DE ASEO'            , 'N');
insert into tipos_productos values (2 , 'ARTICULOS DE ESCRITORIO'      , 'N');
insert into tipos_productos values (3 , 'ARTICULOS DE PERFUMERÍA'      , 'N');
insert into tipos_productos values (4 , 'BEBIDAS GASEOSAS'             , 'N');
insert into tipos_productos values (5 , 'BABIDAS ALCOHÓLICAS'          , 'N');
insert into tipos_productos values (6 , 'CIGARRILLOS'                  , 'N');
insert into tipos_productos values (7 , 'CARNE'                        , 'N');
insert into tipos_productos values (8 , 'PETRÓLEO'                     , 'N');
insert into tipos_productos values (9 , 'BENCINA'                      , 'N');
insert into tipos_productos values (10, 'PARAFINA'                     , 'N');
insert into tipos_productos values (11, 'ALIMENTOS NO PERECIBLES'      , 'N');
insert into tipos_productos values (12, 'ALIMENTOS PERECIBLES FRUTAS'  , 'N');
insert into tipos_productos values (13, 'ALIMENTOS PERECIBLES VERDURAS', 'N');
insert into tipos_productos values (14, 'ALIMENTOS PERECIBLES OTROS'   , 'N');
insert into tipos_productos values (15, 'LIBROS'                       , 'S');

insert into impuestos values (1, 1, 'IMPUESTO AL VALOR AGREGADO'                    , 'IVA' , 'S', 19);
insert into impuestos values (2, 1, 'IMPUESTO ADICIONAL A LAS BEBIDAS ALCOHÓLICAS'  , 'ILA' , 'N', 20);
insert into impuestos values (3, 1, 'IMPUESTO ADICIONAL A LAS BEBIDAS ANALCOHÓLICAS', 'IABA', 'N', 5 );

insert into tipos_productos_impuestos values (1, 4, 3);
insert into tipos_productos_impuestos values (2, 5, 2);

insert into tipos_servicios values (1, 'SERVICIOS PROFESIONALES'   , 'S');
insert into tipos_servicios values (2, 'SERVICIOS NO PROFESIONALES', 'N');

insert into tipos_formas_pagos values (1, 'EFECTIVO'       );
insert into tipos_formas_pagos values (2, 'TARJETA CRÉDITO');
insert into tipos_formas_pagos values (3, 'TARJETA DÉBITO' );
insert into tipos_formas_pagos values (4, 'CHEQUE'         );
insert into tipos_formas_pagos values (5, 'LETRA'          );
insert into tipos_formas_pagos values (6, 'VALE VISTA'     );

\q
